apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter-notebook
  namespace: jlab
  labels:
    name: jupyter-notebook
spec:
  replicas: 3
  selector:
    matchLabels:
      name: jupyter-notebook
  template:
    metadata:
      labels:
        name: jupyter-notebook
    spec:
      securityContext:
        runAsUser: 0
        fsGroup: 0
      containers:
        - name: jupyter-notebook
          image: jupyter/datascience-notebook:latest
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 8888
          command:
            - /bin/bash
            - -c
            - |
              start.sh jupyter lab --LabApp.token='password' --LabApp.ip='0.0.0.0' --LabApp.allow_root=True
          volumeMounts:
            - name: jupyterlab-data
              mountPath: /home/jovyan
          resources:
            requests:
              memory: 500Mi
              cpu: 250m
      restartPolicy: Always
      volumes:
      - name: jupyterlab-data
        persistentVolumeClaim:
          claimName: jupyterlab-pvc