
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: dev
data:
  APP_COLOR: green
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: sex-pod
  name: sex-pod-service
  namespace: dev
spec:
  ports:
  - port: 500
    protocol: TCP
    targetPort: 80
  selector:
    run: sexpod
  type: LoadBalancer
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: sex-pod
  name: sex-pod
  namespace: dev
spec:
  containers:
  - image: jmugu/dockerapp
    name: sex-pod
    envFrom:
    - configMapRef:
        name: app-config
    ports:
    - containerPort: 80
  