apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend-app
  namespace: dev
  labels:
    app: guestbook
    tier: frontend-app
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      tier: frontend-app
  template:
    metadata:
      labels:
        tier: frontend-app
    spec:
      containers:
      - name: php-redis
        image: jmugu/dockerapp 
