apiVersion: v1
kind: Pod
metadata:
  name: frontendapp
spec:
  containers:
  - name: app
    image: eproject/web
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
  - name: log-aggregator
    image: eproject/web
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
